### ISSUE TITLE
Definition of "proposition"

### ISSUE THREAD

**Issue by jcguu95** [dcernst/IBL-IntroToProof#143]
Thanks for the great work! My students and I enjoy the book so
far :D -- We're using version Fall 2021. Students and I got a bit
confused with a thing in section 2.2.

First, the definition of a *proposition* is given in 2.16, which
says

> A proposition is a sentence that is either true or false but
  never both.

This is very clear. Following this, "n = 4" should not be a
proposition, while "There is a real number n such that n = 4."
is.

However, in definition 2.18 it introduces operators on
propositions, one of which is "If A, then B." I want to provide
some examples to the students, but all I can come up with are
things like "If n = 2, then n^2 = 4". However, this is not a
legit example because both

+ A = "n = 2"
+ B = "n^2 = 4"

are not propositions. On the other hand, these kind of examples
show up a lot.. so I don't really know what to tell my students.
Any thoughts?

**Comment by dcernst** [comment]
Oops, sorry for the slow response.  I was in Disneyland;)

This is always an issue.  There is an implicit "For all..." in front of all statements like "If n = 2, then n^2 = 4."  That is, there is an implicit universal quantifier in front of all statements of the form "if A(x), then B(x)", where A(x) and B(x) are predicates and x is some variable.  I attempt to address this issue just after Problem 2.67.  Perhaps it comes too late?  The timing of this has always worked for me (or I mention it earlier while I am teaching), but feedback welcome.

**Comment by jcguu95** [comment]
Thanks for your response! Hope you had fun in Disneyland :)

If I understand correctly, should I understand the statement "If n=2, then n^2=4." as the statement in the form "If (A),then (B).", where (A) and (B) are both **propositions** [1] with

+ (A) == "there exists some integer n such that n=2"
+ (B) == "there exists some integer n such that n^2=4"

This seems good to me, as (A) and (B) are both propositions! One thing to address though, is that the symbol `n` appearing both in (A) and (B) should be treated as the same thing in the statement `(A) => (B)`. I guess this is worth mentioning?

By the way, since time does not permit, we didn't go over all problems carefully :P 

[1] Recall that a proposition is defined to be a sentence that is either true or false, but not both.

**Comment by dcernst** [comment]
There is probably a way to correctly interpret things as you are attempting.  However, I think the proper way to interpret things in your example is as follows.  Let A(n) and B(n) be predicates with variable n give by:

A(n):= "n=2"
B(n):= "n^2=4"

The definition of predicate appears at the beginning of Section 2.4.  Notice that predicates are not propositions since their truth value depends on n.  We can turn predicates in propositions by either assigning a value(s) to the variable or quantifying the variable using the universal quantifier ("for all...") or the existential quantifier ("there exists...such that..."). We can also combine predicates and then quantify (or some combination of the two: quantify and the combine, combine and then quantify, or some combo of both in complicated situations).  Sometimes variables are implicitly bound by context or by a previous sentence.

The statement "For all n, if A(n), then B(n)" is in fact a proposition.  This statement may sometimes be written in two sentences, where the first sentence bounds the variable: "Let n be a natural number. If A(n), then B(n)."  Another way to write the same statement would be "If n is a natural number such that A(n), then B(n)." This is how most of the theorems in Sections 2.1 and 2.3 are written. More commonly, if the universe of discourse is understood (or can be inferred), one might simply write "If A(n), then B(n)." 

Officially, "If A(n), then B(n)" is a predicate, but if we take this as short hand for "For all n, if A(n), then B(n)", we have a proposition.  Of course, in the example we have in play, the universal quantifier isn't doing very much since the hypothesis is n=2.

One detail that I sweep under the rug is that we discuss the truth value of conditional propositions in Definition 2.18 and then take for granted that we can apply the same structure to conditional statements involving predicates.  My personal take is that I don't want to get bogged down in these sorts of pedantic details, but in thinking about it carefully now, I do think this discussion is at least worthy of a remark in the book.  I'll add a separate issue in GitHub to remind me to add a comment at some point.  I'm also going to work on an instructor's manual this summer, so I'll be sure to address this in the manual, as well.

Out of curiosity, where are you teaching and who is your audience?

**Comment by jcguu95** [comment]
I see; that's great! So "If A(n), then B(n)." does not make formal sense before 2.4. But in 2.4, we extend the operators from propositions to predicates.

I'm teaching some grad students (aspiring math teachers) at Stony Brook University :)
