### ISSUE TITLE
Universal quantification versus implication issues

### ISSUE THREAD

**Issue by StevenGubkin** [dcernst/IBL-IntroToProof#79]
I am using your text for a 6 week Intro proof summer course.

One of my students points out that 

"For example, Theorem 2.3 states, “The sum of two consecutive integers is odd.” We can reword this theorem as, “If x ∈ Z, then x + (x + 1) is odd.”

is technically incorrect because x is not a bound variable, so x ∈ Z is not a proposition.   We probably should write "For all x ∈ Z, x+(x+1) is odd".  I understand that we use this language as mathematicians, but I think it is technically incorrect and could cause confusion for some students.  Therefore I would move

"Exercise 2.27. Reword Theorem 2.23 so that it explicitly reads as a conditional statement."

to the section on quantification, and modify it:

Reword Theorem 2.23 so that it explicitly reads as a universally quantified statement.

**Comment by dcernst** [comment]
Sorry for the very slow response!  I'm happy to hear that you are using the book.  

While I agree with the formality, I think I prefer the discussion and messiness that arises in light of this situation. In particular, it reflects the reality of how most mathematicians write (unfortunately). I do attempt to resolve the situation in the blurb following Exercise 2.72 (version Spring 2020):

http://danaernst.com/teaching/mat320s20/IntroToProof.pdf

With that being said, I'm not opposed to moving the exercise you cited. However, I think things are a bit more complicated than that if we are going to truly resolve the issue (since there are many implicit "For all..." leading up to the blurb following 2.72.

The AMS plans to publish the book (while maintaining the open source license and allowed a free version to continue to survive online) and I have many issues to attend to from the editorial board. So, this summer is the time to add this to the todo pile.

Thoughts?

**Comment by dcernst** [comment]
Done.
